// GENERATED by scripts/sync-web.mjs from web src/lib/checkin.ts + components/Stars.tsx @0081e66. DO NOT EDIT: change the web file or the patch in the script.
export const DENIED: Record<string, { title: string; detail: string }> = {
  not_enrolled: { title: "Not on the list", detail: "You're not registered for this class at this centre." },
  not_invited: { title: "Not invited", detail: "This class is for invited students only. Ask your instructor if you should be here." },
  payment_required: { title: "Payment due", detail: "Pay your next instalment to join this class." },
  makeup_not_open: { title: "Not yet", detail: "Make-up classes open once your own classes have ended." },
  not_a_missed_class: { title: "Not your class", detail: "This isn't a class you missed, so there's nothing to make up." },
  makeup_limit_reached: { title: "No make-ups left", detail: "You've used all your make-up classes." },
};

export const CHECKIN_OPENS_MIN = 30;

export const REASON_LABEL: Record<string, string> = {
  not_enrolled: "Not registered", not_invited: "Not invited", payment_required: "Payment due", makeup_not_open: "Make-up not open",
  not_a_missed_class: "Not a missed class", makeup_limit_reached: "No make-ups left",
};

export const RATING_WORDS = ["", "Poor", "Fair", "Good", "Very good", "Excellent"] as const;
