// GENERATED by scripts/routes.mjs from port/route-manifest.json. DO NOT EDIT.
export const GUARDS: Record<string, string[]> = {
  "/class-messages": [
    "admin",
    "super_admin"
  ],
  "/check-ins": [
    "admin",
    "super_admin"
  ],
  "/reviews": [
    "admin",
    "super_admin"
  ],
  "/roster": [
    "admin",
    "super_admin"
  ],
  "/custom": [
    "admin",
    "super_admin",
    "instructor"
  ],
  "/my-classes": [
    "instructor"
  ],
  "/schedule": [
    "instructor",
    "coordinator",
    "centre_director",
    "admin",
    "super_admin"
  ],
  "/students": [
    "coordinator",
    "centre_director"
  ],
  "/centre-classes": [
    "coordinator",
    "centre_director"
  ],
  "/statement": [
    "centre_director"
  ]
};
