// GENERATED by scripts/sync-web.mjs from web src/lib/nav.ts @64bc5f7. DO NOT EDIT: change the web file or the patch in the script.
import type { IconName } from "@/ui/Icon";
export type NavItem = [to: string, label: string, icon: IconName];

export const TABS: Record<string, NavItem[]> = {
  student: [["/", "Home", "home"], ["/messages", "Messages", "messages"], ["/enrol", "Enrol", "enrol"]],
  instructor: [["/", "Today", "today"], ["/my-classes", "My classes", "classes"], ["/schedule", "Schedule", "schedule"], ["/history", "History", "history"], ["/messages", "Messages", "messages"]],
  coordinator: [["/", "Home", "home"], ["/students", "Students", "users"], ["/centre-classes", "Classes", "classes"]],
  centre_director: [["/", "Home", "home"], ["/students", "Students", "users"], ["/centre-classes", "Classes", "classes"], ["/statement", "Statement", "receipt"], ["/team", "Team", "userPlus"]],
  admin: [["/", "Overview", "overview"], ["/users", "Users", "users"], ["/announce", "Announce", "announce"], ["/manage", "Manage", "manage"]],
};
TABS.super_admin = TABS.admin;

// What the bottom bar and the role's own pages don't reach. A role with nothing here has no hamburger.
export const MENU_EXTRA: Record<string, NavItem[]> = {
  instructor: [["/custom", "Custom class", "calendarPlus"]],
};
