// GENERATED by scripts/sync-web.mjs from web src/lib/nav.ts + components/NavMenu.tsx @0081e66. DO NOT EDIT: change the web file or the patch in the script.
import type { IconName } from "@/ui/Icon";
export type NavItem = [to: string, label: string, icon: IconName];

export const TABS: Record<string, NavItem[]> = {
  student: [["/", "Home", "home"], ["/messages", "Messages", "messages"]],
  instructor: [["/", "Today", "today"], ["/my-classes", "My classes", "classes"], ["/schedule", "Schedule", "schedule"], ["/history", "History", "history"], ["/messages", "Messages", "messages"]],
  admin: [["/", "Overview", "overview"], ["/users", "Users", "users"], ["/announce", "Announce", "announce"], ["/manage", "Manage", "manage"]],
};
TABS.super_admin = TABS.admin;

// Drawer shortcuts the tab bar doesn't have.
export const EXTRA: Record<string, NavItem[]> = {
  student: [["/enrol", "Enrol in a course", "enrol"]],
  centre_director: [["/team", "My team", "userPlus"]],
  instructor: [["/custom", "Custom class", "calendarPlus"]],
};
