#!/usr/bin/env node
// scripts/routes.mjs
//   node scripts/routes.mjs            create stub files for every manifest route/home that has no file yet (never overwrites), regenerate src/shell/guards.generated.ts
//   node scripts/routes.mjs --check    compare the web app's <Route path="…"> list with the manifest; exit 1 if the web has routes the manifest doesn't know (route drift)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const m = JSON.parse(readFileSync(join(root, "port/route-manifest.json"), "utf8"));
const title = (s) => s.replace(/^\(?\w+\)?\//, "").replace(/\[|\]|\.tsx|index/g, "").replace(/[-/]/g, " ").trim() || "Home";

if (process.argv.includes("--check")) {
  const web = resolve(process.env.WEB_REPO ?? join(root, "..", "iqacademy"));
  const app = readFileSync(join(web, "src/App.tsx"), "utf8");
  const paths = [...new Set([...app.matchAll(/<Route path="([^"]+)"/g)].map((x) => x[1].replace(/\?$/, "")))].filter((p) => p !== "*");
  const known = new Set(m.routes.map((r) => r.web));
  const optional = (p) => p.replace(/\/:id\?$/, ""); // "/messages/:id?" is two native routes
  const missing = paths.filter((p) => !known.has(p) && !known.has(optional(p)) && p !== "/emergency" && p !== "/");
  if (missing.length) { console.error("Web routes with no manifest entry:\n  " + missing.join("\n  ")); process.exit(1); }
  console.log(`route check ok: ${paths.length} web routes, all in the manifest`);
  process.exit(0);
}

const write = (rel, text) => { const f = join(root, rel); if (existsSync(f)) return false; mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, text); console.log("created", rel); return true; };
for (const r of m.routes) {
  if (r.stub === false) continue;
  const plain = !r.file.startsWith("(app)"); // signed-out / root screens have no header, bell or tab bar
  write(`src/app/${r.file}`, `// ROUTE STUB (M5). Owner: ${r.module}. Web source: ${r.page}\n// Replace the body with the real screen and keep the default export. Role guards live in port/route-manifest.json, not here.\n${plain ? "// This screen is outside the signed-in shell: it has no header or tab bar, so do not use <Screen>.\n" : ""}import { Placeholder } from "@/shell/Placeholder";\n\nexport default function Route() {\n  return <Placeholder module="${r.module}" title="${title(r.file)}" web="${r.page}"${plain ? " plain" : ""} />;\n}\n`);
}
for (const h of m.homes) {
  write(h.component, `// HOME STUB (M5). Owner: ${h.module}. Web source: ${h.page}\n// Replace the body with the real home screen and keep the named export. It renders inside the shell's <Screen>.\nimport { Placeholder } from "@/shell/Placeholder";\n\nexport function ${h.export}() {\n  return <Placeholder module="${h.module}" title="${h.export.replace(/([A-Z])/g, " $1").trim()}" web="${h.page}" bare />;\n}\n`);
}
const guards = Object.fromEntries(m.routes.filter((r) => r.guard).map((r) => [r.web, r.guard]));
writeFileSync(join(root, "src/shell/guards.generated.ts"), `// GENERATED by scripts/routes.mjs from port/route-manifest.json. DO NOT EDIT.\nexport const GUARDS: Record<string, string[]> = ${JSON.stringify(guards, null, 2)};\n`);
console.log("guards written");
