#!/usr/bin/env node
// scripts/sync-web.mjs — regenerate everything that is derived from the web app's source.
//   node scripts/sync-web.mjs            (web checkout: $WEB_REPO or ../iqacademy)
// Outputs (all start with a GENERATED header; never edit them, change the web file or the patch below):
//   src/shared/web/*      pure libs: time (patched for Hermes tz), centre, roster, channels, db, password (patched), error messages, check-in constants
//   src/ui/icons.generated.tsx   the web icon set as react-native-svg
// Patches use replaceOnce(): if the web file stops matching, this script FAILS instead of silently diverging.
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const web = resolve(process.env.WEB_REPO ?? join(root, "..", "iqacademy"));
const sha = execSync("git rev-parse --short HEAD", { cwd: web }).toString().trim();
const read = (p) => readFileSync(join(web, p), "utf8");
const out = (p, text) => { const f = join(root, p); mkdirSync(dirname(f), { recursive: true }); writeFileSync(f, text); console.log("wrote", p); };
const header = (src) => `// GENERATED by scripts/sync-web.mjs from web ${src} @${sha}. DO NOT EDIT: change the web file or the patch in the script.\n`;

function replaceOnce(src, find, repl, what) {
  const i = src.indexOf(find);
  if (i < 0) throw new Error(`sync-web: patch "${what}" no longer matches the web source. Update scripts/sync-web.mjs.`);
  if (src.indexOf(find, i + 1) >= 0) throw new Error(`sync-web: patch "${what}" matches more than once.`);
  return src.slice(0, i) + repl + src.slice(i + find.length);
}
function between(src, startMark, endMark, what) {
  const a = src.indexOf(startMark); if (a < 0) throw new Error(`sync-web: start marker for ${what} not found`);
  const b = endMark ? src.indexOf(endMark, a) : src.length; if (b < 0) throw new Error(`sync-web: end marker for ${what} not found`);
  return src.slice(a, b);
}
// Balanced extraction of one `export const NAME ... ;` statement (string/brace aware).
function statement(src, re, what) {
  const m = re.exec(src); if (!m) throw new Error(`sync-web: ${what} not found`);
  let i = m.index, depth = 0, q = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (q) { if (c === "\\") i++; else if (c === q) q = null; continue; }
    if (c === '"' || c === "'" || c === "`") { q = c; continue; }
    if ("{[(".includes(c)) depth++; else if ("}])".includes(c)) depth--;
    else if (c === ";" && depth === 0) { i++; break; }
  }
  return src.slice(m.index, i);
}

// ---- time.ts (patched) ----
{
  let s = read("src/lib/time.ts");
  s = replaceOnce(s, 'import { supabase } from "./supabase";', 'import { fetchServerNow } from "../clockSource";', "time: import");
  s = replaceOnce(s, 'await supabase.rpc("server_now")', "await fetchServerNow()", "time: server_now");
  const oldFmt = between(s, "const cache = new Map<string, Intl.DateTimeFormat>();", "type D = string | number | Date;", "time: fmt");
  const newFmt = `// ---- native patch: Hermes may lack Africa/Lagos tz data. Detected once; if unsupported we shift +1h and format as UTC (Lagos is UTC+1, no DST). ----
type TzMode = "intl" | "shifted";
const LAGOS_OFFSET_MS = 3600000;
let tzMode: TzMode | null = null;
function lagosSupported(): boolean {
  try {
    const p = new Intl.DateTimeFormat("en-GB", { timeZone: TZ, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(Date.UTC(2026, 0, 1, 0, 30));
    return p.find((x) => x.type === "hour")?.value === "01" && p.find((x) => x.type === "minute")?.value === "30";
  } catch { return false; }
}
/** "intl" when the engine knows Africa/Lagos, "shifted" when we have to emulate it. Shown in the spike screen. */
export const tzStrategy = (): TzMode => (tzMode ??= lagosSupported() ? "intl" : "shifted");
/** Tests only. */
export const __forceTzStrategy = (m: TzMode | null) => { tzMode = m; cache.clear(); };
type Fmt = { format(d: Date | number): string; formatToParts(d: Date | number): Intl.DateTimeFormatPart[] };
const cache = new Map<string, Fmt>();
function fmt(o: Intl.DateTimeFormatOptions, tz: string = TZ, locale?: string): Fmt {
  const shifted = tz === TZ && tzStrategy() === "shifted";
  const k = \`\${locale ?? ""}|\${tz}|\${shifted}|\${JSON.stringify(o)}\`;
  let f = cache.get(k);
  if (!f) {
    const inner = new Intl.DateTimeFormat(locale, { timeZone: shifted ? "UTC" : tz, ...o });
    const at = (d: Date | number) => (shifted ? (d instanceof Date ? d.getTime() : d) + LAGOS_OFFSET_MS : d);
    f = { format: (d) => inner.format(at(d)), formatToParts: (d) => inner.formatToParts(at(d)) };
    cache.set(k, f);
  }
  return f;
}
`;
  s = s.replace(oldFmt, newFmt);
  s += `\n/** Native: restore the last measured skew at start-up so countdowns are right before the first sync finishes. */\nexport const setClockSkew = (ms: number) => { skew = ms; };\n`;
  out("src/shared/web/time.ts", header("src/lib/time.ts") + s);
}

// ---- verbatim pure libs ----
for (const f of ["centre", "roster", "channels", "db"]) out(`src/shared/web/${f}.ts`, header(`src/lib/${f}.ts`) + read(`src/lib/${f}.ts`));

// ---- password.ts (patched random source) ----
{
  let s = read("src/lib/password.ts");
  s = replaceOnce(s, "crypto.getRandomValues(buf)", "getRandomValues(buf)", "password: random");
  s = replaceOnce(s, "export type Rule", 'import { getRandomValues } from "expo-crypto";\nexport type Rule', "password: import");
  out("src/shared/web/password.ts", header("src/lib/password.ts") + s);
}

// ---- error wording: MESSAGES + friendly/UserMessage/rawMessage (naira is hand-written, see src/shared/format.ts) ----
{
  const s = read("src/lib/supabase.ts");
  const messages = between(s, "const MESSAGES: Record<string, string> = {", "/** A message that is already written for people.", "MESSAGES");
  const fns = between(s, "/** A message that is already written for people.", "export const naira", "friendly");
  out("src/shared/web/errors.ts", header("src/lib/supabase.ts") + messages + fns + "export { MESSAGES };\n");
}

// ---- check-in constants + rating words ----
{
  const c = read("src/lib/checkin.ts");
  const parts = [
    statement(c, /export const DENIED\b/, "DENIED"),
    statement(c, /export const CHECKIN_OPENS_MIN\b/, "CHECKIN_OPENS_MIN"),
    statement(c, /export const REASON_LABEL\b/, "REASON_LABEL"),
    statement(read("src/components/Stars.tsx"), /export const RATING_WORDS\b/, "RATING_WORDS"),
  ];
  out("src/shared/web/consts.ts", header("src/lib/checkin.ts + components/Stars.tsx") + parts.join("\n\n") + "\n");
}

// ---- icons ----
{
  const s = read("src/components/Icon.tsx");
  const body = between(s, "type Layers = {", "type Props =", "icons");
  const tags = "path|rect|circle|g|ellipse|line|polyline|polygon";
  const rn = body
    .replace(new RegExp(`<(${tags})(?=[\\s/>])`, "g"), (_, t) => `<${t[0].toUpperCase()}${t.slice(1)}`)
    .replace(new RegExp(`</(${tags})>`, "g"), (_, t) => `</${t[0].toUpperCase()}${t.slice(1)}>`);
  out("src/ui/icons.generated.tsx",
    header("src/components/Icon.tsx") +
    `import type { ReactNode } from "react";\nimport { Circle, Ellipse, G, Line, Path, Polygon, Polyline, Rect } from "react-native-svg";\nvoid [Ellipse, G, Line, Polygon, Polyline];\n\nexport ` + rn.replace(/^type Layers/, "type Layers").replace("const ICONS", "export const ICONS"));
}
// ---- colour tokens (index.css custom properties → RGB triplets) ----
{
  const css = read("src/index.css");
  const grab = (sel) => {
    const m = css.match(new RegExp(sel + "\\s*\\{([^}]*)\\}"));
    if (!m) throw new Error(`sync-web: css block ${sel} not found`);
    const o = {};
    for (const [, k, r, g, b] of m[1].matchAll(/--([a-z-]+):\s*(\d+)\s+(\d+)\s+(\d+)\s*;/g)) o[k] = [+r, +g, +b];
    return o;
  };
  const light = grab(String.raw`:root, \[data-theme="light"\]`), dark = grab(String.raw`\[data-theme="dark"\]`);
  const names = ["bg", "surface", "sunken", "ink", "muted", "line", "accent", "accent-ink", "ok", "warn", "bad", "info"];
  for (const n of names) if (!light[n] || !dark[n]) throw new Error(`sync-web: token --${n} missing`);
  const fmt = (o) => "{ " + names.map((n) => `${JSON.stringify(n)}: [${o[n].join(", ")}]`).join(", ") + " }";
  out("src/theme/tokens.generated.ts", header("src/index.css") + `export type RGB = [number, number, number];\nexport const LIGHT: Record<string, RGB> = ${fmt(light)};\nexport const DARK: Record<string, RGB> = ${fmt(dark)};\n`);
}
// ---- navigation: tab bar per role + the hamburger drawer's leftovers (both in lib/nav.ts) ----
{
  const nav = read("src/lib/nav.ts");
  const tabs = statement(nav, /export const TABS\b/, "TABS");
  const alias = nav.match(/^TABS\.super_admin = TABS\.admin;$/m)?.[0];
  if (!alias) throw new Error("sync-web: TABS.super_admin alias not found");
  const extra = statement(nav, /export const MENU_EXTRA\b/, "MENU_EXTRA");
  out("src/shell/nav.generated.ts", header("src/lib/nav.ts") +
    `import type { IconName } from "@/ui/Icon";\nexport type NavItem = [to: string, label: string, icon: IconName];\n\n${tabs}\n${alias}\n\n// What the bottom bar and the role's own pages don't reach. A role with nothing here has no hamburger.\n${extra}\n`);
}
writeFileSync(join(root, "port/.web-sha"), sha + "\n");
console.log("web sha", sha);
